import React from 'react';
import { DownloadSimple, FilmStrip, Robot, X } from '@phosphor-icons/react';
import { createTools } from '../../webmcp.js';
import { FORMATS, FORMAT_LABELS } from '../../project.js';
import { IconButton, Modal } from '../controls.jsx';

export function Dialogs({ project, exportOpen, agentOpen, job, busy, agentState, audit, onCloseExport, onCloseAgent, onRender }) {
  return <>{exportOpen && <Modal onClose={onCloseExport} labelledBy="export-heading"><section className="modal"><div className="modal-heading"><FilmStrip size={22}/><IconButton label="Close export dialog" onClick={onCloseExport}><X size={19}/></IconButton></div><h2 id="export-heading">Make it a video.</h2><p>Render the current composition locally. No uploads, accounts or cloud credits.</p><div className="export-summary"><span>{FORMAT_LABELS[project.format]}<small>{FORMATS[project.format].join(' × ')}</small></span><span>{project.duration}s<small>Duration</small></span><span>{project.fps}<small>Frames / sec</small></span></div>{job && <div className={`job-status ${job.state === 'failed' ? 'failed' : ''}`} role="status"><strong>{job.message}</strong>{!['done', 'failed'].includes(job.state) && <progress value={job.progress} max="100"/>}{job.state === 'done' && <a className="export-button" href={job.url} download={`${project.name}.mp4`}><DownloadSimple size={17}/>Download MP4</a>}</div>}<button className="export-button full-width" disabled={busy || !project.images.length} onClick={onRender}>{busy ? 'Rendering locally…' : 'Render MP4'}<DownloadSimple size={17}/></button><p className="helper">Local rendering can take a few minutes. Keep the server running.</p></section></Modal>}
    {agentOpen && <Modal onClose={onCloseAgent} labelledBy="agent-heading"><section className="modal agent-modal"><div className="modal-heading"><Robot size={24}/><IconButton label="Close agent tools" onClick={onCloseAgent}><X size={19}/></IconButton></div><h2 id="agent-heading">Built for agents, too.</h2><p>Native WebMCP tools use the same validated project actions as the editor.</p><div className="native-status"><span className={`status-dot ${agentState === 'Connected' ? 'saved' : ''}`}/>{agentState === 'Unavailable' ? 'WebMCP is not available in this browser.' : `WebMCP · ${agentState}`}</div><p className="helper">Requires a browser and agent that support document.modelContext. Nothing is enabled through browser flags automatically.</p><div className="tool-list">{createTools({}).map(tool => <div key={tool.name}><code>{tool.name}</code><span>{tool.annotations.readOnlyHint ? 'READ' : 'ACTION'}</span></div>)}</div><p className="helper">Exports require a click in the app. New carousel and shader implementations are added in source, never evaluated from uploaded code.</p>{audit.length > 0 && <div className="audit"><h3>Recent agent actions</h3>{audit.map((entry, index) => <div key={index}><code>{entry.name}</code><span>{entry.time}</span></div>)}</div>}</section></Modal>}</>;
}
