import React from 'react';
import { ArrowDown, ArrowUp, Circle, ImageSquare, Images, MusicNotes, Plus, Sparkle, Stack, TextT, X } from '@phosphor-icons/react';
import { cardMediaKind, cardVideoSource } from '../../card-media.js';
import { LayerList } from './LayerList.jsx';
import { LayoutControls } from './LayoutControls.jsx';
import { FORMATS, FORMAT_LABELS, carouselImages } from '../../project.js';
import { Field, IconButton, NumberField, Section } from '../controls.jsx';

const layerIcons = { background: ImageSquare, carousel: Images, text: TextT, logo: Sparkle, music: MusicNotes, media: ImageSquare, model: Circle };

export function LayerPanel({ project, selected, leftTab, uploading, onSelectLayer, onSetLeftTab, onPatch, onOpenAdd, onRemoveLayer, onMoveLayer, onDropLayer, onDuplicateLayer, onChangeProject, onChangeDuration, onChangeFps, onReorderImage, onRemoveImage }) {
  const layer = project.layers.find(item => item.id === selected);
  const carousels = project.layers.filter(item => item.type === 'carousel');
  const carousel = layer?.type === 'carousel' ? layer : carousels[0];
  const images = carouselImages(project, carousel);
  return <aside className="left-panel panel"><div className="tabs"><button className={leftTab === 'layers' ? 'selected' : ''} onClick={() => onSetLeftTab('layers')}><Stack size={15}/>Layers</button><button className={leftTab === 'media' ? 'selected' : ''} onClick={() => onSetLeftTab('media')}><Images size={15}/>Media</button></div>
    {leftTab === 'layers' ? <><div className="section-heading"><h2>Composition</h2><div className="layer-heading-actions"><span>{project.layers.length} layers</span><IconButton label="Move layer forward" onClick={() => onMoveLayer(1)} disabled={!layer || layer.locked || project.layers.at(-1)?.id === selected}><ArrowUp size={15}/></IconButton><IconButton label="Move layer backward" onClick={() => onMoveLayer(-1)} disabled={!layer || layer.locked || project.layers[0]?.id === selected}><ArrowDown size={15}/></IconButton></div></div><LayerList project={project} selected={selected} icons={layerIcons} onSelect={onSelectLayer} onPatch={onPatch} onMove={onMoveLayer} onDrop={onDropLayer} onDuplicate={onDuplicateLayer} onRemove={onRemoveLayer}/><button className="outline-button add-layer" disabled={uploading} onClick={onOpenAdd}><Plus size={16}/>Add layer</button>
      <Section title="Canvas"><Field label="Aspect ratio"><div className="segmented canvas-formats">{Object.keys(FORMATS).map(format => <button key={format} className={project.format === format ? 'selected' : ''} onClick={() => onChangeProject({ ...project, format })}>{FORMAT_LABELS[format]}</button>)}</div></Field><NumberField label="Duration (s)" value={project.duration} min={1} max={30} onChange={onChangeDuration}/><Field label="Frame rate"><select aria-label="Frame rate" value={project.fps} onChange={event => onChangeFps(Number(event.target.value))}><option value={24}>24 fps</option><option value={30}>30 fps</option><option value={60}>60 fps</option></select></Field></Section></> : <><div className="section-heading"><h2>Carousel media</h2><span>{images.length} / 24</span></div><Field label="Carousel"><select aria-label="Carousel media layer" value={carousel?.id ?? ''} disabled={!carousels.length} onChange={event => onSelectLayer(event.target.value)}>{!carousels.length && <option value="">No carousel</option>}{carousels.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><div className="asset-grid">{images.map((image, index) => <div className="asset" key={image.id}>{cardMediaKind(image.src) === 'image' ? <img src={image.src} alt={image.name}/> : <><video className="asset-video" src={cardVideoSource(image.src)} muted playsInline preload="metadata" aria-label={image.name}/><span className="asset-kind">{cardMediaKind(image.src) === 'gif' ? 'GIF' : 'VIDEO'}</span></>}<span className="asset-number">{String(index + 1).padStart(2, '0')}</span><div className="asset-actions"><IconButton label={`Move image ${index + 1} earlier`} onClick={() => onReorderImage(index, -1)} disabled={index === 0}><ArrowUp size={13}/></IconButton><IconButton label={`Move image ${index + 1} later`} onClick={() => onReorderImage(index, 1)} disabled={index === images.length - 1}><ArrowDown size={13}/></IconButton><IconButton label={`Remove image ${index + 1}`} onClick={() => onRemoveImage(index)}><X size={13}/></IconButton></div></div>)}</div><button className="outline-button add-layer" disabled={uploading} onClick={onOpenAdd}><Plus size={16}/>Add layer</button>{!images.length && <p className="helper">No media added</p>}</>}
    {leftTab === 'layers' && <LayoutControls project={project} onChange={onChangeProject}/>}

  </aside>;
}
