import React from 'react';
import { ArrowDown, ArrowUp, Circle, ImageSquare, Images, MusicNotes, Plus, Sparkle, Stack, TextT, X, UploadSimple } from '@phosphor-icons/react';
import { cardMediaKind, cardVideoSource } from '../../card-media.js';
import { LayerList } from './LayerList.jsx';
import { LayoutControls } from './LayoutControls.jsx';
import { FORMATS, FORMAT_LABELS } from '../../project.js';
import { Field, IconButton, NumberField, Section } from '../controls.jsx';

const layerIcons = { background: ImageSquare, carousel: Circle, text: TextT, logo: Sparkle, music: MusicNotes };

export function LayerPanel({ project, selected, leftTab, uploading, onSelectLayer, onSetLeftTab, onPatch, onAddText, onMoveLayer, onDropLayer, onDuplicateLayer, onChangeProject, onChangeDuration, onChangeFps, onPick, onReorderImage, onRemoveImage }) {
  return <aside className="left-panel panel"><div className="tabs"><button className={leftTab === 'layers' ? 'selected' : ''} onClick={() => onSetLeftTab('layers')}><Stack size={15}/>Layers</button><button className={leftTab === 'media' ? 'selected' : ''} onClick={() => onSetLeftTab('media')}><Images size={15}/>Media</button></div>
    {leftTab === 'layers' ? <><div className="section-heading"><h2>Composition</h2><span>{project.layers.length} layers</span></div><LayerList project={project} selected={selected} icons={layerIcons} onSelect={onSelectLayer} onPatch={onPatch} onMove={onMoveLayer} onDrop={onDropLayer} onDuplicate={onDuplicateLayer}/><button className="outline-button add-layer" disabled={project.layers.length >= 20} onClick={onAddText}><Plus size={16}/>Add text layer</button>
      <Section title="Canvas"><Field label="Aspect ratio"><div className="segmented canvas-formats">{Object.keys(FORMATS).map(format => <button key={format} className={project.format === format ? 'selected' : ''} onClick={() => onChangeProject({ ...project, format })}>{FORMAT_LABELS[format]}</button>)}</div></Field><NumberField label="Duration (s)" value={project.duration} min={1} max={30} onChange={onChangeDuration}/><Field label="Frame rate"><select aria-label="Frame rate" value={project.fps} onChange={event => onChangeFps(Number(event.target.value))}><option value={24}>24 fps</option><option value={30}>30 fps</option><option value={60}>60 fps</option></select></Field></Section></> : <><div className="section-heading"><h2>Carousel media</h2><span>{project.images.length} / 24</span></div><button className="upload-zone" disabled={uploading || project.images.length >= 24} onClick={() => onPick('images', 'image/png,image/jpeg,image/webp,image/gif,image/avif,video/mp4,video/webm', true)}><UploadSimple size={24}/><strong>{uploading ? 'Uploading…' : 'Add media'}</strong><span>Up to 75 MB per file</span></button><div className="asset-grid">{project.images.map((image, index) => <div className="asset" key={image.id}>{cardMediaKind(image.src) === 'image' ? <img src={image.src} alt={image.name}/> : <><video className="asset-video" src={cardVideoSource(image.src)} muted playsInline preload="metadata" aria-label={image.name}/><span className="asset-kind">{cardMediaKind(image.src) === 'gif' ? 'GIF' : 'VIDEO'}</span></>}<span className="asset-number">{String(index + 1).padStart(2, '0')}</span><div className="asset-actions"><IconButton label={`Move image ${index + 1} earlier`} onClick={() => onReorderImage(index, -1)} disabled={index === 0}><ArrowUp size={13}/></IconButton><IconButton label={`Move image ${index + 1} later`} onClick={() => onReorderImage(index, 1)} disabled={index === project.images.length - 1}><ArrowDown size={13}/></IconButton><IconButton label={`Remove image ${index + 1}`} onClick={() => onRemoveImage(index)}><X size={13}/></IconButton></div></div>)}</div></>}
    {leftTab === 'layers' && <LayoutControls project={project} onChange={onChangeProject}/>}

  </aside>;
}
