import React, { useCallback, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Play, Pause, SkipBack, Plus, ArrowUp, ArrowDown, X, Eye, EyeSlash, Stack, Images, TextT, MusicNotes, Circle, ImageSquare, DownloadSimple, FloppyDisk, UploadSimple, SlidersHorizontal, Robot, Check, Warning, Cube, Sparkle, FilmStrip, ArrowCounterClockwise, CaretUp, CaretDown } from '@phosphor-icons/react';
import '@fontsource/geist/400.css'; import '@fontsource/geist/600.css'; import '@fontsource/geist/800.css';
import './style.css';
import { demoProject, validateProject, FORMATS, TEMPLATES, SHADERS, patchLayer, resizeDuration } from './project.js';
import { createScene, stageMarkup } from './scene.js';
import { BRAND } from './brand.js';
import { registerWebMCP, createTools } from './webmcp.js';
import { PlacementMap } from './placement-map.jsx';
import { TimelineTracks } from './timeline.jsx';

async function request(url, options) { const res = await fetch(url, options); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Request failed.'); return data; }
const layerIcons = { background: ImageSquare, carousel: Circle, text: TextT, logo: Sparkle, music: MusicNotes };
const formatLabels = { square: '1 : 1', portrait: '9 : 16', landscape: '16 : 9' };
const timeLabel = seconds => `${Math.floor(seconds / 60).toString().padStart(2, '0')}:${Math.floor(seconds % 60).toString().padStart(2, '0')}.${Math.floor(seconds * 10 + 0.00001) % 10}`;
function Field({ label, children, value }) { return <div className="field"><div className="field-label"><span>{label}</span>{value !== undefined && <output>{value}</output>}</div>{children}</div>; }
function Range({ label, value, min, max, step = 1, suffix = '', onChange }) {
  const display = `${Number(value).toFixed(step < 1 ? 2 : 0)}${suffix}`;
  const progress = Math.max(0, Math.min(1, (value - min) / (max - min)));
  return <label className="field integrated-range" style={{ '--range-progress': progress }}>
    <span className="range-fill" aria-hidden="true"/>
    <span className="range-ticks" aria-hidden="true">{[0, 1, 2, 3, 4].map(i => <i key={i}/>)}</span>
    <span className="range-label">{label}</span>
    <input aria-label={label} aria-valuetext={display} type="range" min={min} max={max} step={step} value={value} onChange={e => onChange(Number(e.target.value))}/>
    <output>{display}</output>
  </label>;
}
function Color({ label, value, onChange }) { return <Field label={label}><div className="color-field"><input aria-label={label} type="color" value={value} onChange={e => onChange(e.target.value)}/><span>{value.toUpperCase()}</span></div></Field>; }
function NumberField({ label, value, min, max, step = 1, onChange }) { return <Field label={label}><input aria-label={label} type="number" min={min} max={max} step={step} value={value} onChange={e => { const n = Number(e.target.value); if (n >= min && n <= max) onChange(n); }}/></Field>; }
function Section({ title, children }) { return <section className="property-section"><h3>{title}</h3>{children}</section>; }
function IconButton({ label, children, ...props }) { return <button type="button" className="icon-button" aria-label={label} title={label} {...props}>{children}</button>; }
function Stage({ project, time, playing, onError, onReady, positionPreview }) {
  const holder = useRef(); const root = useRef(); const engine = useRef(); const timeRef = useRef({ time, playing });
  timeRef.current = { time, playing };
  useEffect(() => {
    const [w, h] = FORMATS[project.format];
    let cancelled = false; let loaded;
    root.current.innerHTML = stageMarkup(project);
    const fit = () => { if (!holder.current || !root.current) return; const box = holder.current.getBoundingClientRect(); const scale = Math.min((box.width - 24) / w, (box.height - 24) / h); root.current.style.width = `${w}px`; root.current.style.height = `${h}px`; root.current.style.transform = `translate(-50%,-50%) scale(${Math.max(0.05, scale)})`; };
    const observer = new ResizeObserver(fit); observer.observe(holder.current); fit();
    onReady(false);
    createScene(root.current, project).then(scene => { loaded = scene; if (cancelled) scene.dispose(); else { engine.current = scene; scene.seek(timeRef.current.time, timeRef.current.playing); onReady(true); } }).catch(error => { if (!cancelled) onError(error.message); });
    return () => { cancelled = true; observer.disconnect(); engine.current = null; loaded?.dispose(); };
  }, [project, onError, onReady]);
  useEffect(() => { engine.current?.seek(time, playing); }, [time, playing]);
  useEffect(() => {
    // Editor-only positioning preview; the project and GPU scene change once per gesture.
    for (const l of project.layers.filter(l => ['text', 'logo'].includes(l.type))) {
      const node = [...root.current.querySelectorAll('[data-floc-layer]')].find(n => n.dataset.flocLayer === l.id);
      if (!node) continue;
      const pos = positionPreview?.id === l.id ? positionPreview : l;
      node.style.left = `${pos.x}%`; node.style.top = `${pos.y}%`;
    }
  }, [positionPreview, project]);
  return <div ref={holder} className="stage-holder"><div ref={root} className="stage" aria-label="Video composition preview"/></div>;
}
function Modal({ children, onClose, labelledBy }) {
  const ref = useRef();
  useEffect(() => { const dialog = ref.current; dialog.showModal(); return () => dialog.close(); }, []);
  return <dialog ref={ref} className="modal-backdrop" aria-labelledby={labelledBy} onCancel={e => { e.preventDefault(); onClose(); }}>{children}</dialog>;
}
function TemplateMini({ template }) { return <div className={`template-mini ${template}`} aria-hidden="true">{[0,1,2,3,4].map(i => <span key={i} style={{ '--i': i }}/>)}</div>; }
function App() {
  const [project, setProject] = useState(demoProject); const projectRef = useRef(project); const revision = useRef(0); const saveQueue = useRef(Promise.resolve());
  const [loaded, setLoaded] = useState(false); const [status, setStatus] = useState('Loading project'); const [error, setError] = useState('');
  const [selected, setSelected] = useState('carousel'); const [leftTab, setLeftTab] = useState('layers'); const [rightTab, setRightTab] = useState('composition');
  const [time, setTime] = useState(0.65); const [playing, setPlaying] = useState(false); const [ready, setReady] = useState(false);
  const [positionPreview, setPositionPreview] = useState(null);
  const [timelineOpen, setTimelineOpen] = useState(true);
  const [uploading, setUploading] = useState(false); const [exportOpen, setExportOpen] = useState(false); const [job, setJob] = useState(null); const jobRef = useRef(null);
  const [agentOpen, setAgentOpen] = useState(false); const [agentState, setAgentState] = useState('Checking'); const [audit, setAudit] = useState([]); const fileInput = useRef(); const fileTarget = useRef('images'); const importInput = useRef();
  const [history, setHistory] = useState([]); const hydrated = useRef(false);
  const layer = project.layers.find(l => l.id === selected) || project.layers.find(l => l.type === 'carousel');
  const carousel = project.layers.find(l => l.type === 'carousel');
  const showError = useCallback(message => setError(message), []);
  const sceneReady = useCallback(value => setReady(value), []);
  const previewPosition = useCallback(value => { setPositionPreview(value); if (value) setPlaying(false); }, []);
  const change = useCallback(next => {
    try { const valid = validateProject(next); const previous = projectRef.current; setHistory(h => [...h.slice(-19), previous]); projectRef.current = valid; setProject(valid); setStatus('Unsaved changes'); setError(''); } catch (e) { setError(e.message); }
  }, []);
  function patch(id, fields) { try { change(patchLayer(projectRef.current, id, fields)); } catch (e) { setError(e.message); } }
  const save = useCallback(() => {
    const snapshot = projectRef.current;
    const action = saveQueue.current.catch(() => {}).then(async () => { const result = await request('/api/project', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ project: snapshot, revision: revision.current }) }); revision.current = result.revision; if (snapshot === projectRef.current) setStatus('Saved locally'); });
    saveQueue.current = action; return action;
  }, []);
  useEffect(() => { request('/api/project').then(data => { const p = validateProject(data.project); projectRef.current = p; setProject(p); revision.current = data.revision; hydrated.current = true; setLoaded(true); setStatus('Saved locally'); }).catch(e => { setError(e.message); setStatus('Offline'); }); }, []);
  useEffect(() => { if (!loaded || !hydrated.current) return; const timer = setTimeout(() => save().catch(e => { setError(e.message); setStatus('Save failed'); }), 650); return () => clearTimeout(timer); }, [project, loaded, save]);
  useEffect(() => { if (!playing) return; const start = performance.now() - time * 1000; let frame; const tick = now => { const next = (now - start) / 1000; if (next >= projectRef.current.duration) { setTime(0); setPlaying(false); } else { setTime(next); frame = requestAnimationFrame(tick); } }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [playing]);
  useEffect(() => { if (time > project.duration) setTime(0); }, [project.duration, time]);
  useEffect(() => {
    if (!loaded) return;
    const registration = registerWebMCP({ get: () => projectRef.current, set: next => { const p = validateProject(next); change(p); }, save,
      seek: t => { setPlaying(false); setTime(t); }, audit: name => setAudit(a => [{ name, time: new Date().toLocaleTimeString() }, ...a].slice(0, 8)), requestExport: () => { setPlaying(false); setExportOpen(true); }, exportStatus: () => jobRef.current || { state: 'idle' } });
    setAgentState(registration.supported ? 'Connecting' : 'Unavailable');
    registration.ready.then(() => { if (registration.supported) setAgentState('Connected'); }).catch(e => { setAgentState('Registration failed'); setError(e.message); });
    return () => registration.dispose();
  }, [loaded, change, save]);
  useEffect(() => { jobRef.current = job; if (!job || ['done', 'failed'].includes(job.state)) return; const timer = setTimeout(() => request(`/api/exports/${job.id}`).then(setJob).catch(e => setError(e.message)), 1200); return () => clearTimeout(timer); }, [job]);
  async function upload(files, target) {
    setUploading(true); setError('');
    try {
      const values = [];
      for (const f of files) values.push(await request(`/api/assets?name=${encodeURIComponent(f.name)}`, { method: 'POST', headers: { 'Content-Type': f.type || 'application/octet-stream' }, body: f }));
      if (target === 'images') change({ ...projectRef.current, images: [...projectRef.current.images, ...values.map(({ id, src, name }) => ({ id, src, name }))] });
      else { const item = values[0]; const l = projectRef.current.layers.find(l => l.id === target); patch(target, { src: item.src, ...(l.type === 'background' ? { mode: item.type.startsWith('video') ? 'video' : 'image' } : {}) }); }
    } catch (e) { setError(e.message); } finally { setUploading(false); }
  }
  function pick(target, accept, multiple = false) { fileTarget.current = target; fileInput.current.accept = accept; fileInput.current.multiple = multiple; fileInput.current.click(); }
  function addText() { const p = projectRef.current; const id = crypto.randomUUID(); change({ ...p, layers: [...p.layers, { id, type: 'text', name: 'New text', visible: true, start: 0, end: p.duration, text: 'Your next idea.', x: 8, y: 76, size: 42, color: BRAND.colors.white, weight: 600, width: 78, animation: 'fade' }] }); setSelected(id); setLeftTab('layers'); }
  function reorderImage(index, delta) { const images = [...project.images]; const next = index + delta; if (next < 0 || next >= images.length) return; [images[index], images[next]] = [images[next], images[index]]; change({ ...project, images }); }
  function moveLayer(delta) { const layers = [...project.layers]; const i = layers.findIndex(l => l.id === selected); const to = i + delta; if (to < 0 || to >= layers.length) return; [layers[i], layers[to]] = [layers[to], layers[i]]; change({ ...project, layers }); }
  function downloadProject() { const blob = new Blob([JSON.stringify(projectRef.current, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'floc-motion-project.json'; a.click(); URL.revokeObjectURL(url); }
  async function render() { setPlaying(false); setError(''); try { const result = await request('/api/exports', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ project: projectRef.current }) }); setJob(result); } catch (e) { setError(e.message); } }
  const busy = job && !['done', 'failed'].includes(job.state);
  return <main className="app-shell">
    <input ref={fileInput} hidden type="file" onChange={e => { if (e.target.files.length) upload([...e.target.files], fileTarget.current); e.target.value = ''; }}/>
    <input ref={importInput} hidden type="file" accept="application/json,.json" onChange={async e => { const f = e.target.files[0]; if (f) { try { change(validateProject(JSON.parse(await f.text()))); } catch (err) { setError(err.message); } } e.target.value = ''; }}/>
    <header className="topbar"><a href="/" className="brand" aria-label="FLOC Motion home"><img src={BRAND.assets.wordmarkWhite} width="91.23" height="20" alt="FLOC"/><em>MOTION</em></a><span className="internal-label">INTERNAL STUDIO <span className="version">01</span></span><div className="header-actions"><span className="save-state"><span className={status === 'Saved locally' ? 'status-dot saved' : 'status-dot'}/>{status}</span><button className="subtle-button agent-button" onClick={() => setAgentOpen(true)}><Robot size={17}/>Agent tools<span className={`small-dot ${agentState === 'Connected' ? 'active' : ''}`}/></button><IconButton label="Import project" onClick={() => importInput.current.click()}><UploadSimple size={18}/></IconButton><IconButton label="Download project JSON" onClick={downloadProject}><DownloadSimple size={18}/></IconButton><button className="export-button" onClick={() => { setPlaying(false); setExportOpen(true); }} disabled={!loaded}><DownloadSimple size={17}/>Export video</button></div></header>
    {error && <div className="error-banner" role="alert"><Warning size={16}/>{error}<IconButton label="Dismiss error" onClick={() => setError('')}><X/></IconButton></div>}
    <div className="workspace">
      <aside className="left-panel panel"><div className="tabs"><button className={leftTab === 'layers' ? 'selected' : ''} onClick={() => setLeftTab('layers')}><Stack size={15}/>Layers</button><button className={leftTab === 'media' ? 'selected' : ''} onClick={() => setLeftTab('media')}><Images size={15}/>Media</button></div>
        {leftTab === 'layers' ? <><div className="section-heading"><h2>Composition</h2><span>{project.layers.length} layers</span></div><div className="layer-list">{[...project.layers].reverse().map(l => { const Icon = layerIcons[l.type]; return <div key={l.id} className={`layer-row ${selected === l.id ? 'active' : ''}`}><button className="layer-select" onClick={() => setSelected(l.id)}><Icon size={18}/><span>{l.name}<small>{l.type === 'carousel' ? TEMPLATES.find(t => t.id === l.template).name : l.type === 'music' && !l.src ? 'No track added' : l.type}</small></span></button><IconButton label={`${l.visible ? 'Hide' : 'Show'} ${l.name}`} onClick={() => patch(l.id, { visible: !l.visible })}>{l.visible ? <Eye size={15}/> : <EyeSlash size={15}/>}</IconButton></div>; })}</div><button className="outline-button add-layer" onClick={addText}><Plus size={16}/>Add text layer</button><div className="layer-order"><span>Layer order</span><IconButton label="Move layer forward" onClick={() => moveLayer(1)} disabled={project.layers.at(-1)?.id === selected}><ArrowUp size={15}/></IconButton><IconButton label="Move layer backward" onClick={() => moveLayer(-1)} disabled={project.layers[0]?.id === selected}><ArrowDown size={15}/></IconButton></div>
        <Section title="Canvas"><Field label="Aspect ratio"><div className="segmented">{Object.keys(FORMATS).map(f => <button key={f} className={project.format === f ? 'selected' : ''} onClick={() => change({ ...project, format: f })}>{formatLabels[f]}</button>)}</div></Field><NumberField label="Duration (seconds)" value={project.duration} min={1} max={30} onChange={n => change(resizeDuration(project, n))}/><Field label="Frame rate"><select aria-label="Frame rate" value={project.fps} onChange={e => change({ ...project, fps: Number(e.target.value) })}><option value={24}>24 fps · cinematic</option><option value={30}>30 fps · smooth</option></select></Field></Section></> : <><div className="section-heading"><h2>Carousel images</h2><span>{project.images.length} / 24</span></div><button className="upload-zone" disabled={uploading || project.images.length >= 24} onClick={() => pick('images', 'image/png,image/jpeg,image/webp,image/gif,image/avif', true)}><UploadSimple size={24}/><strong>{uploading ? 'Uploading…' : 'Add your images'}</strong><span>PNG, JPG, WEBP · up to 75 MB</span></button><div className="asset-grid">{project.images.map((img, i) => <div className="asset" key={img.id}><img src={img.src} alt={img.name}/><span className="asset-number">{String(i + 1).padStart(2, '0')}</span><div className="asset-actions"><IconButton label={`Move image ${i + 1} earlier`} onClick={() => reorderImage(i, -1)} disabled={i === 0}><ArrowUp size={13}/></IconButton><IconButton label={`Move image ${i + 1} later`} onClick={() => reorderImage(i, 1)} disabled={i === project.images.length - 1}><ArrowDown size={13}/></IconButton><IconButton label={`Remove image ${i + 1}`} onClick={() => change({ ...project, images: project.images.filter((_, n) => n !== i) })}><X size={13}/></IconButton></div></div>)}</div>{!project.images.length && <p className="helper">Add images to bring the carousel to life.</p>}<p className="helper">Image order is shared across every template. Resources stay on this computer.</p></>}
        <div className="panel-footer"><span className="status-dot saved"/>Local workspace<span>V 0.1</span></div>
      </aside>
      <section className="center-panel"><div className="canvas-toolbar"><div><input aria-label="Project name" className="project-name" maxLength={100} value={project.name} onChange={e => change({ ...project, name: e.target.value })}/><span className="helper">COMPOSITION / {TEMPLATES.find(t => t.id === carousel.template).name.toUpperCase()}</span></div><div className="canvas-meta"><span>{FORMATS[project.format].join(' × ')}</span><IconButton label="Undo last edit" disabled={!history.length} onClick={() => { const previous = history.at(-1); projectRef.current = previous; setProject(previous); setHistory(h => h.slice(0, -1)); setStatus('Unsaved changes'); }}><ArrowCounterClockwise size={17}/></IconButton></div></div><div className="preview-wrap"><Stage project={project} positionPreview={positionPreview} time={time} playing={playing} onError={showError} onReady={sceneReady}/>{!ready && <div className="preview-loading">Preparing composition…</div>}</div><div className="preview-caption"><span><Cube size={14}/>Real-time WebGL preview</span><span>{SHADERS.find(s => s.id === carousel.shader).name} / {project.fps} FPS</span></div></section>
      <aside className="right-panel panel"><div className="tabs"><button className={rightTab === 'composition' ? 'selected' : ''} onClick={() => setRightTab('composition')}>Composition</button><button className={rightTab === 'animation' ? 'selected' : ''} onClick={() => setRightTab('animation')}>Animation</button></div><div className="section-heading"><h2>{layer.name}</h2><SlidersHorizontal size={16}/></div>
        {layer.type === 'carousel' && <>{rightTab === 'composition' ? <><Section title="Template"><div className="template-grid">{TEMPLATES.map(t => <button key={t.id} className={`template-option ${layer.template === t.id ? 'selected' : ''}`} onClick={() => patch(layer.id, { template: t.id, ...(t.id === 'arc' ? { roll: 0, tilt: 0 } : {}) })}><TemplateMini template={t.id}/><span>{t.name}{layer.template === t.id && <Check size={12}/>}</span></button>)}</div></Section><Section title="Cards"><Range label="Card size" value={layer.size} min={0.5} max={2.5} step={0.05} onChange={n => patch(layer.id, { size: n })}/><Range label="Gap" value={layer.gap} min={0} max={1} step={0.02} onChange={n => patch(layer.id, { gap: n })}/>{layer.template === 'circular' && <Range label="Curvature" value={layer.curve} min={0} max={1} step={0.05} onChange={n => patch(layer.id, { curve: n })}/>}<button className="outline-button" onClick={() => setLeftTab('media')}><Images size={15}/>Edit carousel images</button></Section><Section title="Camera"><Range label="Tilt" value={layer.tilt} min={-65} max={65} suffix="°" onChange={n => patch(layer.id, { tilt: n })}/><Range label="Rotation" value={layer.roll} min={-90} max={90} suffix="°" onChange={n => patch(layer.id, { roll: n })}/><div className="two-fields"><Range label="Position X" value={layer.x} min={10} max={90} onChange={n => patch(layer.id, { x: n })}/><Range label="Position Y" value={layer.y} min={10} max={90} onChange={n => patch(layer.id, { y: n })}/></div></Section></> : <Section title="Motion"><Range label="Speed" value={layer.speed} min={-90} max={90} suffix="°/s" onChange={n => patch(layer.id, { speed: n })}/><p className="helper">Negative values reverse the direction. All motion is seekable and frame-driven.</p></Section>}<Section title="Shader"><Field label="Effect"><select aria-label="Shader effect" value={layer.shader} onChange={e => patch(layer.id, { shader: e.target.value })}>{SHADERS.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>{layer.shader !== 'none' && <Range label="Intensity" value={layer.intensity} min={0} max={1} step={0.05} onChange={n => patch(layer.id, { intensity: n })}/>} {layer.shader === 'duotone' && <Color label="Shader tint" value={layer.tint} onChange={c => patch(layer.id, { tint: c })}/>}<p className="helper">Applied to cards only. Type and logos stay clear.</p></Section></>}
        {layer.type === 'background' && <Section title="Background"><Field label="Source"><div className="segmented">{['color','image','video'].map(mode => <button key={mode} className={layer.mode === mode ? 'selected' : ''} onClick={() => patch(layer.id, { mode, ...(mode !== 'color' && mode !== layer.mode ? { src: '' } : {}) })}>{mode}</button>)}</div></Field><Color label="Base color" value={layer.color} onChange={c => patch(layer.id, { color: c })}/>{layer.mode !== 'color' && <><button className="outline-button" disabled={uploading} onClick={() => pick(layer.id, layer.mode === 'video' ? 'video/mp4,video/webm' : 'image/png,image/jpeg,image/webp,image/avif')}><UploadSimple size={15}/>{layer.src ? 'Replace media' : `Upload ${layer.mode}`}</button>{layer.src && <p className="helper">Local media loaded</p>}<Field label="Fit"><select aria-label="Background fit" value={layer.fit} onChange={e => patch(layer.id, { fit: e.target.value })}><option value="cover">Fill / crop</option><option value="contain">Fit inside</option></select></Field>{layer.mode === 'video' && <><NumberField label="Video source offset" value={layer.offset} min={0} max={3600} step={0.1} onChange={n => patch(layer.id, { offset: n })}/><label className="check-field"><input type="checkbox" checked={layer.loop} onChange={e => patch(layer.id, { loop: e.target.checked })}/>Loop video · audio muted</label></>}</>}</Section>}
        {layer.type === 'text' && <><Section title="Content"><Field label="Text"><textarea aria-label="Layer text" maxLength={500} rows={4} value={layer.text} onChange={e => patch(layer.id, { text: e.target.value })}/></Field><Range label="Font size" value={layer.size} min={12} max={180} onChange={n => patch(layer.id, { size: n })}/><Field label="Weight"><select aria-label="Font weight" value={layer.weight} onChange={e => patch(layer.id, { weight: Number(e.target.value) })}><option value={400}>Regular</option><option value={600}>Semibold</option><option value={800}>Extra bold</option></select></Field><Color label="Text color" value={layer.color} onChange={c => patch(layer.id, { color: c })}/><Range label="Text width" value={layer.width} min={5} max={100} suffix="%" onChange={n => patch(layer.id, { width: n })}/></Section><Section title="Placement"><PlacementMap project={project} layer={layer} onCommit={fields => patch(layer.id, fields)} onPreview={previewPosition}/><details className="precise-position"><summary>Precise position</summary><Range label="Position X" value={layer.x} min={0} max={95} suffix="%" onChange={n => patch(layer.id, { x: n })}/><Range label="Position Y" value={layer.y} min={0} max={95} suffix="%" onChange={n => patch(layer.id, { y: n })}/></details><Field label="Entrance"><select aria-label="Text entrance" value={layer.animation} onChange={e => patch(layer.id, { animation: e.target.value })}><option value="none">None</option><option value="fade">Fade</option><option value="rise">Rise</option></select></Field></Section></>}
        {layer.type === 'logo' && <Section title="Brand mark"><button className="outline-button" disabled={uploading} onClick={() => pick(layer.id, 'image/png,image/jpeg,image/webp')}><UploadSimple size={15}/>Replace logo</button><p className="helper">Use a transparent PNG or WEBP.</p><Range label="Logo size" value={layer.size} min={2} max={35} suffix="%" onChange={n => patch(layer.id, { size: n })}/><PlacementMap project={project} layer={layer} onCommit={fields => patch(layer.id, fields)} onPreview={previewPosition}/><details className="precise-position"><summary>Precise position</summary><Range label="Position X" value={layer.x} min={0} max={95} suffix="%" onChange={n => patch(layer.id, { x: n })}/><Range label="Position Y" value={layer.y} min={0} max={95} suffix="%" onChange={n => patch(layer.id, { y: n })}/></details></Section>}
        {layer.type === 'music' && <Section title="Soundtrack"><button className="upload-zone" disabled={uploading} onClick={() => pick(layer.id, 'audio/mpeg,audio/wav,audio/mp4,audio/ogg')}><MusicNotes size={24}/><strong>{layer.src ? 'Replace soundtrack' : 'Add a music track'}</strong><span>MP3, WAV, M4A, OGG</span></button><Range label="Volume" value={layer.volume} min={0} max={1} step={0.05} onChange={n => patch(layer.id, { volume: n })}/><NumberField label="Audio source offset" value={layer.offset} min={0} max={3600} step={0.1} onChange={n => patch(layer.id, { offset: n })}/><Range label="Fade in / out" value={layer.fade} min={0} max={5} step={0.1} suffix="s" onChange={n => patch(layer.id, { fade: n })}/><label className="check-field"><input type="checkbox" checked={layer.loop} onChange={e => patch(layer.id, { loop: e.target.checked })}/>Loop music</label>{layer.src && <button className="text-button" onClick={() => patch(layer.id, { src: '' })}>Remove music</button>}</Section>}
        <Section title="Layer timing"><div className="two-fields"><NumberField label="Start (s)" value={layer.start} min={0} max={layer.end - 0.01} step={0.1} onChange={n => patch(layer.id, { start: n })}/><NumberField label="End (s)" value={layer.end} min={layer.start + 0.01} max={project.duration} step={0.1} onChange={n => patch(layer.id, { end: n })}/></div>{layer.type === 'text' && <button className="text-button danger" onClick={() => { change({ ...project, layers: project.layers.filter(l => l.id !== layer.id) }); setSelected(carousel.id); }}>Remove text layer</button>}</Section>
      </aside>
    </div>
    <section className="timeline-panel" aria-label="Timeline"><div className="transport"><div className="transport-controls"><IconButton label="Back to start" onClick={() => { setTime(0); setPlaying(false); }}><SkipBack size={18}/></IconButton><IconButton label={playing ? 'Pause preview' : 'Play preview'} onClick={() => setPlaying(v => !v)} disabled={!ready}>{playing ? <Pause size={20} weight="fill"/> : <Play size={20} weight="fill"/>}</IconButton><span className="timecode">{timeLabel(time)}<span>/ {timeLabel(project.duration)}</span></span></div><input type="range" aria-label="Timeline playhead" min={0} max={project.duration - 0.001} step={0.01} value={time} onChange={e => { setPlaying(false); setTime(Number(e.target.value)); }}/><span className="timeline-label">{project.fps} FPS</span><button className="timeline-toggle" aria-expanded={timelineOpen} aria-controls="timeline-tracks" onClick={() => setTimelineOpen(v => !v)}>{timelineOpen ? <CaretDown size={14}/> : <CaretUp size={14}/>}Timeline</button></div><div id="timeline-tracks" hidden={!timelineOpen}><TimelineTracks project={project} selected={selected} time={time} icons={layerIcons} onSelect={id => { setSelected(id); setPlaying(false); }} onSeek={t => { setTime(t); setPlaying(false); }} onCommit={patch}/></div></section>
    {exportOpen && <Modal onClose={() => setExportOpen(false)} labelledBy="export-heading"><section className="modal"><div className="modal-heading"><FilmStrip size={22}/><IconButton label="Close export dialog" onClick={() => setExportOpen(false)}><X size={19}/></IconButton></div><h2 id="export-heading">Make it a video.</h2><p>Render the current composition locally. No uploads, accounts or cloud credits.</p><div className="export-summary"><span>{formatLabels[project.format]}<small>{FORMATS[project.format].join(' × ')}</small></span><span>{project.duration}s<small>Duration</small></span><span>{project.fps}<small>Frames / sec</small></span></div>{job && <div className={`job-status ${job.state === 'failed' ? 'failed' : ''}`} role="status"><strong>{job.message}</strong>{!['done','failed'].includes(job.state) && <progress value={job.progress} max="100"/>}{job.state === 'done' && <a className="export-button" href={job.url} download={`${project.name}.mp4`}><DownloadSimple size={17}/>Download MP4</a>}</div>}<button className="export-button full-width" disabled={busy || !project.images.length} onClick={render}>{busy ? 'Rendering locally…' : 'Render MP4'}<DownloadSimple size={17}/></button><p className="helper">Local rendering can take a few minutes. Keep the server running.</p></section></Modal>}
    {agentOpen && <Modal onClose={() => setAgentOpen(false)} labelledBy="agent-heading"><section className="modal agent-modal"><div className="modal-heading"><Robot size={24}/><IconButton label="Close agent tools" onClick={() => setAgentOpen(false)}><X size={19}/></IconButton></div><h2 id="agent-heading">Built for agents, too.</h2><p>Native WebMCP tools use the same validated project actions as the editor.</p><div className="native-status"><span className={`status-dot ${agentState === 'Connected' ? 'saved' : ''}`}/>{agentState === 'Unavailable' ? 'WebMCP is not available in this browser.' : `WebMCP · ${agentState}`}</div><p className="helper">Requires a browser and agent that support document.modelContext. Nothing is enabled through browser flags automatically.</p><div className="tool-list">{createTools({}).map(t => <div key={t.name}><code>{t.name}</code><span>{t.annotations.readOnlyHint ? 'READ' : 'ACTION'}</span></div>)}</div><p className="helper">Exports require a click in the app. New carousel and shader implementations are added in source, never evaluated from uploaded code.</p>{audit.length > 0 && <div className="audit"><h3>Recent agent actions</h3>{audit.map((a,i) => <div key={i}><code>{a.name}</code><span>{a.time}</span></div>)}</div>}</section></Modal>}
  </main>;
}
createRoot(document.getElementById('root')).render(<App/>);
